/** Original candidate-word pools for the terminal hack. Common English words, uppercase. */

const SEVEN = `
ABILITY ABSENCE ACADEMY ACCOUNT ACHIEVE ACQUIRE ADDRESS ADVANCE ADVISED AGAINST
ANCIENT ANOTHER ANXIETY ANYBODY ARRANGE ARRIVAL ARTICLE ATTEMPT ATTRACT AVERAGE
BALANCE BARRIER BATTERY BEARING BECAUSE BEDROOM BELIEVE BENEATH BENEFIT BESIDES
BETWEEN BILLION BROTHER BROUGHT BURNING CABINET CALIBER CAPABLE CAPITAL CAPTAIN
CAPTURE CAREFUL CARRIER CAUTION CEILING CENTRAL CENTURY CERTAIN CHAMBER CHANNEL
CHAPTER CHARTER CHICKEN CIRCUIT CLASSIC CLIMATE CLOTHES COLLECT COLLEGE COMBINE
COMFORT COMMAND COMMENT COMPACT COMPANY COMPARE COMPLEX CONCEPT CONCERN CONDUCT
CONFIRM CONNECT CONTACT CONTAIN CONTENT CONTEST CONTROL CONVERT CORRECT COUNCIL
COUNTER COUNTRY CRYSTAL CULTURE CURIOUS CURRENT DECLINE DEFAULT DEFENSE DELIVER
DENSITY DEPOSIT DESPITE DESTROY DEVELOP DIAMOND DIGITAL DISPLAY DISTANT DIVERSE
DRAWING DYNAMIC EASTERN ECONOMY EDITION ELEMENT ENHANCE EVENING EXACTLY EXAMINE
EXAMPLE EXCITED EXHIBIT EXPLAIN EXPLORE EXPRESS EXTREME FACTORY FAILURE FASHION
FEATURE FEELING FICTION FIFTEEN FINANCE FINDING FISHING FOREIGN FOREVER FORMULA
FORTUNE FORWARD FOUNDER FREEDOM FURTHER GALLERY GATEWAY GENERAL GENUINE GREATER
HEADING HEALTHY HEARING HELPFUL HIGHWAY HISTORY HOLIDAY HOUSING HOWEVER HUNDRED
IMAGINE IMPROVE INCLUDE INITIAL INQUIRY INSIGHT INSTALL INSTANT INSTEAD INTENSE
JOURNAL JOURNEY JUSTICE KITCHEN LANDING LEADING LEISURE LIBERTY LIBRARY LICENSE
LIMITED LOGICAL LOYALTY MACHINE MANAGER MASSIVE MAXIMUM MEANING MEASURE MEDICAL
MEETING MESSAGE MILLION MINERAL MINIMUM MISSION MISTAKE MIXTURE MONITOR MORNING
MYSTERY NATURAL NEITHER NETWORK NEUTRAL NOTHING NUCLEAR OBVIOUS OFFICER OPENING
OPERATE OPINION OPTICAL OUTCOME OUTDOOR OUTLOOK OUTSIDE OVERALL PACKAGE PARTNER
PASSAGE PASSION PATIENT PATTERN PAYMENT PENDING PERFECT PERFORM PERHAPS PICTURE
PIONEER PLASTIC POPULAR PORTION PRECISE PREDICT PREMIUM PREPARE PRESENT PREVENT
PRIMARY PRINTER PRIVATE PROBLEM PROCEED PROCESS PRODUCE PRODUCT PROFILE PROGRAM
PROJECT PROMISE PROTECT PROTEIN PROVIDE PURPOSE QUARTER RADICAL RAILWAY REACTOR
READING REALITY RECEIPT RECEIVE RECOVER REFLECT REGULAR RELEASE REMAINS REPLACE
REQUEST REQUIRE RESERVE RESOLVE RESPECT RESPOND RESTORE REVENUE REVERSE ROUTINE
SCIENCE SECTION SEGMENT SERIOUS SERVICE SESSION SETTING SEVERAL SHELTER SILENCE
SIMILAR SOCIETY SOMEONE SPEAKER SPECIAL SPECIES STATION STORAGE STRANGE STRETCH
STUDENT SUBJECT SUCCESS SUGGEST SUMMARY SUPPORT SUPREME SURFACE SURPLUS SURVIVE
SUSPECT SUSTAIN TEACHER THEATER THOUGHT THROUGH TONIGHT TRAFFIC TRANSIT TROUBLE
TYPICAL UNIFORM UNKNOWN UNUSUAL UPGRADE VARIETY VARIOUS VEHICLE VENTURE VERSION
VETERAN VICTORY VIRTUAL VISIBLE WARNING WEATHER WEEKEND WELCOME WESTERN WILLING
WINNING WITHOUT WITNESS WORKING WRITING WRITTEN
`

const SIX = `
ACCESS ACTION ANSWER BEACON BORDER BRIDGE BUNKER CANDLE CANYON CASTLE CIRCLE COFFEE
COPPER CORNER COTTON DANGER DESERT DINNER DOCTOR ENERGY ENGINE FILTER FLOWER FOREST
FROZEN GARDEN GOLDEN HAMMER HARBOR HELMET ISLAND JACKET LADDER LEGACY LETTER MARKET
METEOR MIRROR MOTHER NUMBER ORANGE PALACE PARADE PILLAR PLANET POCKET RADIUS RESCUE
RIBBON ROCKET SAFETY SIGNAL SILVER SPIRIT SPRING STATUE STREAM SUMMER SYSTEM TARGET
TICKET TUNNEL VALLEY WINDOW WINTER
`

const FIVE = `
ALARM ANGEL APPLE BADGE BEACH BLADE BRAIN BREAD CABLE CANDY CHAIN CHAIR CLOCK CLOUD
CROWN DREAM EAGLE EARTH FENCE FLAME GHOST GLASS GRAIN HEART HORSE LASER LEMON LIGHT
MAGIC METAL MONEY NIGHT OCEAN PAPER PIANO PLANT POWER RADIO RIVER ROBOT SCOUT SHIRT
SMOKE SOUND SPACE STEEL STONE STORM SUGAR TABLE TIGER TOWER TRAIN VAULT WATER WHEEL
`

const split = (s: string) => s.trim().split(/\s+/)

/** Candidate pools keyed by word length. */
export const WORDS: Readonly<Record<number, readonly string[]>> = {
  5: split(FIVE),
  6: split(SIX),
  7: split(SEVEN),
}
